### ISSUE TITLE
blackconnect vs. black file watcher

### ISSUE THREAD

**Issue by autoferrit** [lensvol/intellij-blackconnect#1]
What is the benefit of this over adding a file watcher that formats the file on save? It works pretty well even with large files. This is the settings I use
![image](https://user-images.githubusercontent.com/89895/82393755-33e9f380-99fc-11ea-8bae-8942375d46c3.png)

**Comment by lensvol** [comment]
Same as with using `blackd` over invoking `black` separately - it saves a little bit of time over starting a new `black` process. Savings can be most noticeable when you work with a lot of files and change them frequently. 

With `File Watchers`, on each file save PyCharm will spawn a new process and that takes time. With this plugin, you have to trigger reformatting manually (for the moment), but the webserver process is already started and only overhead of network connection is paid.

Also, there can be an issue with you updating VCS repo outside of PyCharm and triggering File Watcher for each file, thus spawning a lot of `black` processes.

All that said, at this time "File Watchers" is the more convenient solution since you do not need to start `blackd` by hand and manually trigger re-formatting. Hopefully, that will change soon :)
