### ISSUE TITLE
# fmt: off blocks ignored, reformatted

### ISSUE THREAD

**Issue by waszil** [lensvol/intellij-blackconnect#64]
Consider this code:
```python
# fmt: off
leave_this_alone =       42
# fmt: on
```
It gets reformatted to this when running BlackConect with ctrl+alt+L:
```python
# fmt: off
leave_this_alone = 42


# fmt: on
```

If I run black simply from the terminal to the same file, that works fine.
What am I missing?
(black: 22.10.0, python: 3.9.7, Widows10)

**Comment by lensvol** [comment]
Not sure, probably **blackd** ignores some restrictions that you can put in the comments. Let me check and get back to you!

**Comment by lensvol** [comment]
Strange, but I cannot reproduce it with the version of black you provided (22.10.0).

I pasted provided fragment into a Python file and called _"Reformat Whole File"_ - nothing has been changed.
I tried reformatting it using _"Reformat Selected Fragment"_ - still no change.

Maybe I am missing something? Could you please provide more context about this issue? E.g. can you reproduce it on non-Windows machine?

**Comment by waszil** [comment]
I've played around, and the problem only occurs if I select the "Trigger on code reformat" option.
![image](https://user-images.githubusercontent.com/3670521/201686057-b67f4664-4f3a-4cd3-ab0b-f99c6705dc68.png)
If I use the "Trigger when saving changed files" option, everything works fine.

**Comment by lensvol** [comment]
Thank you, this may help!

**Comment by waszil** [comment]
If I disable the BlackConnect plugin, stop blackd.exe, and perform a Code->Reformat File in PyCharm, the same happens. Based on this I'd say, that maybe the "Trigger on code reformat" option does not even invoke blackd.

**Comment by lensvol** [comment]
It is actually a bit different: call to **blackd** _does happen_ and for that specific example it returns "nothing to be done here" response. This is exactly what is expected in that situation.

However, the way integration with "Code Reformat" feature is written right now is a bit incorrect: in case call can not be made or no changes are needed it will trigger the default PyCharm coffeee reformatter.

I will see what can be done about this shortly!

**Comment by waszil** [comment]
Oh, I see. Thanks a lot!

**Comment by lensvol** [comment]
After looking into this further, I see no way to prevent this from the plugin's side. Due to the integration being written as a "post-processor", the default PyCharm code formatter will always be called no matter what. :(

But there is a workaround:
1. In the _Settings/Preferences_ dialog , go to _Editor | Code Style_.
2. Switch to the _Formatter_ tab and enable the **Turn formatter on/off with markers in code comments** option.
3. Change default markers to `fmt: on` and `fmt: off` respectively.

In this way, you will get the same behaviour from both PyCharm and **black**.

In one of the following releases, the current method of integration in IDE's code reformatted will be replaced with a version that uses another mechanism entirely and will not have this issue.

Hope that helps!

**Comment by waszil** [comment]
Thanks, that'll do the trick.
