### ISSUE TITLE
blackd being called to autoformat non-Python files

### ISSUE THREAD

**Issue by gldnspud** [lensvol/intellij-blackconnect#7]
Blackconnect seems to be having blackd reformat *.json files for me, and it is doing so incorrectly and in conflict with how I need them to be formatted.

If I turn off its "trigger when saving changed files" option, it no longer reformats my JSON.

I have been using blackconnect for a few weeks now, so I'm pretty sure that this is new behavior.

Later I will try to revert from PyCharm 2020.1.4 to 2020.1.3 and see if that makes a difference.

**Comment by lensvol** [comment]
Good catch!

My bad, I've introduced a regression into file save handler during overzealous refactoring. :(

Fixed in https://github.com/lensvol/intellij-blackconnect/commit/8c9cca38d999f6d183de4e96b3c3aab21eb9ecc7 and version [0.4.1](https://github.com/lensvol/intellij-blackconnect/releases/tag/release-0.4.1) has been released. 

It may take couple of days for it to go through JetBrains approval pipeline, though. In the meantime, you can grab new version from GitHub release page and install it manually via "Install plugin from disk".

**Comment by gldnspud** [comment]
Thanks for the quick patch!
