### ISSUE TITLE
"Close Tab" keymap interfers with closing diff tabs with (custom) CTRL+W shortcut

### ISSUE THREAD

**Issue by nonZero** [lensvol/intellij-blackconnect#83]
Following this bug:

https://youtrack.jetbrains.com/issue/IDEA-309403/CtrlF4-CtrlW-shortcut-close-tab-does-not-work-in-diff

I found out BlackConnect has a "Close Tab" keymap:
![image](https://github.com/lensvol/intellij-blackconnect/assets/66484/f0aa6e71-1b59-4294-813f-772e69f2faa6)

It somehow interfers with the way "close diff tab" works if "CTRL+W is defined in the basic "Close Editor Tab" keymap.

Current solution: Remove CTRL+W from blackconnect's "Close Tab" keymap.

(Why does BlackConnect has a "Close Tab" keymap?)

**Comment by lensvol** [comment]
We do not actually have this shortcut mapped explicitly, so I am as weirded out as you are.

The only two shortcuts we use are Alt+Shift+B and Ctrl+Alt+Shift+B:
https://github.com/lensvol/intellij-blackconnect/blob/d5b728dc7f07b97ed4e19c067f9b6ad6a7052b02/src/main/resources/META-INF/plugin.xml#L71

But I was able to verify this on clean IDE installation, will try to look further into it.

**Comment by lensvol** [comment]
As indicated by JB employee in the linked thread, this keymap is actually used by behind-the-scenes action that intercepts the closing of the file tab in order to cancel any ongoing reformatting operations started by the plugin.

Looks like there is a better way of doing this through actions listeners, will work on fixing it soonish.
